[project]
name = "frontend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.29.0",
    "nbformat>=5.10.4",
    "plotly>=6.1.0",
]

[dependency-groups]
notebook = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
]
