[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "mambavision>=1.1.0",
    "torch==2.6",
    "uvicorn[standard]>=0.34.2",
]

[dependency-groups]
notebook = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
]
