[project]
name = "p9-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pillow>=11.1.0",
    "torch>=2.6.0",
]

[dependency-groups]
notebook = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.6",
    "matplotlib>=3.10.1",
]
tf = [
    "tensorflow>=2.19.0",
]
